### ISSUE TITLE
Error calling classFactory() method

### ISSUE THREAD

**Issue by cbertelli** [nextgis/quickmapservices#182]
Hello,
recent versions of QMS do not work on my old QGIS 2.18.14 running under MacOS 10.9.5 and installed with macbrew. This is the output:

ImportError: cannot import name uic 
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis2/2.18.14/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/user/.qgis2/python/plugins/quick_map_services/__init__.py", line 34, in classFactory
    from .quick_map_services import QuickMapServices
  File "/usr/local/Cellar/qgis2/2.18.14/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/user/.qgis2/python/plugins/quick_map_services/quick_map_services.py", line 41, in 
    from .qms_service_toolbox import QmsServiceToolbox
  File "/usr/local/Cellar/qgis2/2.18.14/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/user/.qgis2/python/plugins/quick_map_services/qms_service_toolbox.py", line 8, in 
    from qgis.PyQt import uic
ImportError: cannot import name uic

**Comment by cbertelli** [comment]
Thank you for your prompt reply.
Maybe the issue is due to brew "modernism": python is now python3 and old
python is now python@2, PyQt is now PyQt5 so the old PyQt is now (since a
lot of time) PyQt-Qt4... Starting QGIS2 it finds everything (aliasing). I
understand this is a mess, but until version 0.19.6 it ran without glitches.

**Comment by BishopGIS** [comment]
This is not standard build of QGIS 2. QGIS 2.x ships with python 2. In you case upgrade to QGIS 3 needed I think.

**Comment by cbertelli** [comment]
But until version 0.19.6 of QMS did not find any issue and goig back to version 0.19.4 it runs perfectly despite the awkward build of QGIS 2; anyway it runs with python 2.7.5 internally and finds the right PyQt when searching for it. 
If I open the python console under Plugins menu, and type:
```
 from qgis.PyQt import uic
```
I get:
```
 Traceback (most recent call last):
  File "<input>", line 1, in <module>
 ImportError: cannot import name uic
```

**Comment by 514ckw4r3** [comment]
@cbertelli, is this issue still relevant?

**Comment by cbertelli** [comment]
No, thanks. Since then I began using the official packaging for QGIS3.
Thank you for replying.
c
